import { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router";
import { demoCases } from "../data/cases";
import { Scale, Home, FileText } from "lucide-react";
import { api } from "../utils/api";

export default function FinalJudgment() {
  const { caseId } = useParams();
  const navigate = useNavigate();
  const selectedCase = demoCases.find((c) => c.id === caseId);
  const [isLoading, setIsLoading] = useState(true);
  const [judgment, setJudgment] = useState("");

  useEffect(() => {
    const loadOrGenerateJudgment = async () => {
      try {
        // Try to get existing judgment
        const existingJudgment = await api.getJudgment(caseId);
        setJudgment(existingJudgment.judgment);
        setIsLoading(false);
      } catch (error) {
        // If judgment doesn't exist, generate a new one
        console.log('No existing judgment found, generating new one...');
        
        // Simulate AI processing time
        setTimeout(async () => {
          try {
            // Get messages to pass to judgment generation
            const messages = await api.getMessages(caseId);
            
            // Generate judgment
            const result = await api.generateJudgment(
              caseId,
              selectedCase?.title || "",
              messages.lawyerA || [],
              messages.lawyerB || []
            );
            
            setJudgment(result.judgment);
            setIsLoading(false);
          } catch (genError) {
            console.error('Error generating judgment:', genError);
            setJudgment("Error generating judgment. Please try again.");
            setIsLoading(false);
          }
        }, 3000);
      }
    };

    loadOrGenerateJudgment();
  }, [caseId, selectedCase]);

  if (!selectedCase) {
    return (
      <div className="min-h-screen bg-slate-900 flex items-center justify-center">
        <p className="text-white">Case not found</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 p-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="flex items-center justify-center gap-3 mb-4">
            <Scale className="w-12 h-12 text-amber-400" />
            <h1 className="text-3xl text-white">AI Judge Decision</h1>
          </div>
          <p className="text-slate-300">{selectedCase.title}</p>
        </div>

        {/* Judgment Content */}
        <div className="bg-slate-800 rounded-lg p-8 mb-6 shadow-xl border border-slate-700">
          {isLoading ? (
            <div className="text-center py-12">
              <div className="inline-block animate-spin rounded-full h-12 w-12 border-4 border-amber-400 border-t-transparent mb-4"></div>
              <p className="text-slate-300">AI Judge is analyzing the arguments...</p>
              <p className="text-slate-500 text-sm mt-2">
                Processing legal precedents and case details
              </p>
            </div>
          ) : (
            <div className="space-y-6">
              <div className="flex items-center gap-2 mb-6">
                <FileText className="w-6 h-6 text-amber-400" />
                <h2 className="text-2xl text-white">Official Judgment</h2>
              </div>
              <div className="bg-slate-900 rounded-lg p-6 border border-slate-700">
                <pre className="text-slate-200 whitespace-pre-wrap font-mono text-sm leading-relaxed">
                  {judgment}
                </pre>
              </div>
              <div className="mt-8 pt-6 border-t border-slate-700">
                <p className="text-slate-400 text-sm italic text-center">
                  This judgment was generated by the AI Judge System based on the arguments presented.
                  <br />
                  Generated on {new Date().toLocaleDateString()} at {new Date().toLocaleTimeString()}
                </p>
              </div>
            </div>
          )}
        </div>

        {/* Actions */}
        {!isLoading && (
          <div className="flex justify-center gap-4">
            <button
              onClick={() => navigate("/")}
              className="flex items-center gap-2 px-6 py-3 bg-slate-700 hover:bg-slate-600 text-white rounded-lg transition-colors"
            >
              <Home className="w-5 h-5" />
              Back to Case Selection
            </button>
            <button
              onClick={() => navigate(`/debate/${caseId}`)}
              className="flex items-center gap-2 px-6 py-3 bg-amber-500 hover:bg-amber-600 text-slate-900 rounded-lg transition-colors"
            >
              Review Arguments
            </button>
          </div>
        )}
      </div>
    </div>
  );
}